name: Test
"on":
  push:
    branches:
      - master
      - dependabot/npm_and_yarn/**
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Commit Linter
        uses: wagoid/commitlint-github-action@v2
        with:
          configFile: './package.json'

  npmCi:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - run: npm ci
      - run: npm test
  typecheck:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - run: npm ci
      - run: npm run typecheck
  do-types-need-regenerating:
    name: Do types need to be regenerated?
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - run: npm ci
      - run: npm run build:schema
      - run: npm run build:types
      - run: git status
      - run: |
          git diff --exit-code || bash -c \
            'echo "::error file=schema.d.ts::This needs to be regenerated by running \`build:types\`" && false'
